http:
  port: 8081
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # api:
  #   host: localhost
  #   paths: '/ip'
  ZeroTrustDemoApp:
    host: localhost
    paths: /api/v1/auth/*

  ZeroTrustDemoApp2:
    host: localhost
    paths: /api/v1/user/*

  ZeroTrustAdmin:
    host: localhost
    paths: /api/v1/admin/*
serviceEndpoints:
  ZeroTrustDemoAppService:
    url: 'http://localhost:3000'

  ZeroTrustDemoAppService2:
    url: 'http://localhost:3001'

  ZeroTrustAdminService:
    url: 'http://localhost:4000'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  - name: Auth-API
    apiEndpoints:
      # - api
      ZeroTrustDemoApp
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    - cors:
          - action:
              origin: '*'
              methods: 'GET,POST,PUT,DELETE'
    - key-auth:
    - rate-limit:
        - action:
            max: 1
            windowMs: 1000
    - log:
          - action:
              message: Auth Request received ${req.method} ${req.originalUrl}
    - proxy:
          - action:
              serviceEndpoint: ZeroTrustDemoAppService
              changeOrigin: true

  - name: User-API
  # default:
    apiEndpoints:
      # - api
      ZeroTrustDemoApp2
    policies:
    - cors:
          - action:
              origin: '*'
              methods: 'GET,POST,PUT,DELETE'
    - key-auth:
    - rate-limit:
        - action:
            max: 1
            windowMs: 1000
    - log:
          - action:
              message: User Request received ${req.method} ${req.originalUrl}
    - proxy:
          - action:
              serviceEndpoint: ZeroTrustDemoAppService2
              changeOrigin: true

  - name: Admin-API
  # default:
    apiEndpoints:
      # - api
      ZeroTrustAdmin
    policies:
    - cors:
          - action:
              origin: '*'
              methods: 'GET,POST,PUT,DELETE'
    - key-auth:
    - rate-limit:
        - action:
            max: 1
            windowMs: 1000
    - log:
          - action:
              message: Admin Request received ${req.method} ${req.originalUrl}
    - proxy:
          - action:
              serviceEndpoint: ZeroTrustAdminService
              changeOrigin: true
