http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # api:
  #   host: localhost
  #   paths: '/ip'
  ZeroTrustDemoApp:
    host: localhost
    paths: /api/v1/*
serviceEndpoints:
  # httpbin:
  #   url: 'https://httpbin.org'
  ZeroTrustDemoAppService:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: getting-started
  # default:
    apiEndpoints:
      # - api
      ZeroTrustDemoApp
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    - cors:
          - action:
              origin: '*'
              methods: 'GET,POST,PUT,DELETE'
    - key-auth:
    - rate-limit:
        - action:
            max: 1
            windowMs: 1000
    - log:
          - action:
              message: 'Request received'
    - proxy:
          - action:
              # serviceEndpoint: httpbin 
              # changeOrigin: true
              serviceEndpoint: ZeroTrustDemoAppService
              changeOrigin: true
